
//var treeData = JSON.parse(data);

(function() {

	//alert("inserted self... giggity");
	//$("tr").insertAfter("<td><pre>Overall:</pre></td>");
    var data = '[{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/baron_j100x100.jpg", "name": "Baron, James "},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/allen_jonathan100pix.jpg", "name": "Allen, Jonathan"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/lizpic100pix.jpg", "name": "Allison, Lizabeth"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/bradley_e100pix.jpg", "name": "Bradley, Eric"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/buchser_william_100px.jpg", "name": "Buchser, William"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/case-martha100pix.jpg", "name": "Case, Martha"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/chambers100pix.JPG", "name": "Chambers, Randolph"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/cristol100pix.jpg", "name": "Cristol, Daniel"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/dalgleishthumb.jpg", "name": "Dalgleish, Harmony"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/deberry_doug_thumb.png", "name": "DeBerry, Doug"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/forsyth-mark-thumb.jpg", "name": "Forsyth, Mark"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/heideman100pix.jpg", "name": "Heideman, Paul"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/s_hinton100pix.jpg", "name": "Hinton, Shant"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/WMIconOffset100pix.jpg", "name": "Huber, Sarah"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/kerscher100pix.jpg", "name": "Kerscher, Oliver"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/MDrewLamar100pix.jpg", "name": "LaMar, M. Drew"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/donahue_j100x100.JPG", "name": "Donahue, John "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/halleran_m.jpg", "name": "Halleran, Michael"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/hutton_w100x100.jpg", "name": "Hutton, William "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/irbymassie_g100x100.jpg", "name": "Irby, Georgia"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/jones_j100x100.jpg", "name": "Jones, J. Ward"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/government/_images/faculty-photos/thumbnails/lombardini_thumb.jpg", "name": "Lombardini, John"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/mccall_r100x100.jpg", "name": "McCall, Robin"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/nichols_rthumbnail.jpeg", "name": "Nichols, Robert"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/oakley_j100x100.jpg", "name": "Oakley, John"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/paga_j100x100.jpg", "name": "Paga, Jessica"},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/panoussi_v100x100.jpg", "name": "Panoussi, Vassiliki "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/spaeth_b100x100.jpg", "name": "Spaeth, Barbette "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/stephens_j100x100.jpg", "name": "Stephens, Jessica "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/mollyswetnamburland2thumbnail.png", "name": "Swetnam-Burland, Molly "},
{"department": ["Classical Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/tobolowsky_a100x100.jpg", "name": "Tobolowsky, Andrew"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/leu_m100pix.jpg", "name": "Leu, Matthias"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/miller-katherine100pix.jpg", "name": "Miller, Katherine"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/HelenMicPicThumb.jpg", "name": "Murphy, Helen"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/WMIconOffset100pix.jpg", "name": "Pantel, Jelena"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/puzey-joshua100px.jpg", "name": "Puzey, Joshua"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/rahn-jennifer100.jpg", "name": "Rahn, Jennifer"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/saha100pix.jpg", "name": "Saha, Margaret"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/sanderson100pix.jpg", "name": "Sanderson, S. Laurie"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/WMIconOffset100pix.jpg", "name": "Saunders, Bill "},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/shakes_diane100pix.png", "name": "Shakes, Diane"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/sher-bev100pix.jpg", "name": "Sher, Beverly"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/WMIconOffset100pix.jpg", "name": "Soto, William"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/swaddle100pix.jpg", "name": "Swaddle, John "},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/watts100px.jpg", "name": "Watts, Bryan"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/wawersik100pix.jpg", "name": "Wawersik, Matthew"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/williamson100x100pix.JPG", "name": "Williamson, Kurt"},
{"department": ["Biology"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/zwollo100pix.jpg", "name": "Zwollo, Patty"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/abegazthumb.jpg", "name": "Abegaz, Berhanu"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/butler.jpg", "name": "Butler, Michael"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/chengthumb.jpeg", "name": "Cheng, Tun-jen"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/clemensthumb.jpeg", "name": "Clemens, Clay"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Cleveland_Thumbnail.jpg", "name": "Cleveland, Clayton"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/corney_f.jpg", "name": "Corney, Frederick"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/daileader_p.jpg", "name": "Daileader, Philip"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/dessler_thumb.jpg", "name": "Dessler, David"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/economics/images/Feldman thumbnail.jpg", "name": "Feldman, David"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/hicksthumb.jpg", "name": "Hicks, Robert"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Holmes Photo Thumbnail.png", "name": "Holmes, Marcus"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/stump.jpg", "name": "Karakaya-Stump, Ayfer"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/kitamura.jpg", "name": "Kitamura, Hiroshi"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/koloski_l.jpg", "name": "Koloski, Laurie"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/konefal.jpg", "name": "Konefal, Betsy"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/langholtzthumb.jpeg", "name": "Langholtz, Harvey"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/economics/images/directory/lopresti_j.jpg", "name": "Lopresti, John"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/maliniak_d_thumb.jpg", "name": "Maliniak, Daniel"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/mapp_p.jpg", "name": "Mapp, Paul"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/mullen_thumb.jpg", "name": "Mullen, Rani"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/oakes_thumb.jpg", "name": "Oakes, Amy"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/peterson_thumb.jpg", "name": "Peterson, Sue"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/pickeringthumb.jpeg", "name": "Pickering, Paula"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/PoliquinThumb.jpg", "name": "Poliquin, Etienne"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/Quark_thumb.jpg", "name": "Quark, Amy"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/Katherine.jpg", "name": "Rahman, Katherine"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/roessler_p.jpg", "name": "Roessler, Philip"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/africanastudies/images/faculty/thumbnails/shiferaw, admasu.jpg", "name": "Shiferaw, Admasu"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/shulman_thumb.jpg", "name": "Shushan, Debra"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/smith_d_thumb.jpg", "name": "Smith, Dennis"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/sohonithumb.jpeg", "name": "Sohoni, Deenesh"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/economics/images/directory/throckmorton_n.jpg", "name": "Throckmorton, Nathaniel"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/tierney_thumb.jpg", "name": "Tierney, Michael"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/internationalrelations/images/faculty/thumbnails/A. Maurits van der Veen thumb.jpg", "name": "van der Veen, A. Maurits"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/faculty/vinson_contact.jpg", "name": "Vinson, Robert"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/larrywilkerson_thumb.jpeg", "name": "Wilkerson, Lawrence"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Zhang_Thumbnail.jpg", "name": "Zhang , Hongyu"},
{"department": ["International Relations"], "pic": "http://www.wm.edu/as/history/images/Zutshi Chitralekha-A.JPG", "name": "Zutshi, Chitralekha"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/david_aday_thumb.jpg", "name": "Aday, Jr., David"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/bakhtiari_eylas.jpg", "name": "Bakhtiari, Elyas "},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/basket_deborah.jpg", "name": "Basket, Deborah"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/mendez_j.jpg", "name": "Bickham Mendez, Jennifer"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/shruti.devagan.jpg", "name": "Devgan, Shruti"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/gosinmonikathumb.jpg", "name": "Gosin, Monika"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/hand_j_6.jpg", "name": "Hand, Judith"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/hanley_thumb.jpg", "name": "Hanley, Caroline"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/jenkins_k_thumb1.jpg", "name": "Jenkins, Kathleen"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/BrentKaup_thumb.jpg", "name": "Kaup, Brent"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/dean/teaching_awards/past-recipients/2014-awards/linneman/linneman-t-170.jpg", "name": "Linneman, Thomas J."},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/ousey_j_thumb.jpg", "name": "Ousey, Graham C."},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/ozyegin_g_thumb.bmp", "name": "Ozyegin, Gul"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/AmyQuark.jpg", "name": "Quark, Amy"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/saporito_s_thumb.jpg", "name": "Saporito, Salvatore"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/sohoni_d_thumb.jpg", "name": "Sohoni, Deenesh"},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/sohoni_t_thumb.jpg", "name": "Sohoni, Tracy "},
{"department": ["Sociology"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/stiman_meaghan.jpg", "name": "Stiman, Meaghan"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/alexangeloveditededited.jpg", "name": "Angelov, Alexander"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/annie blazeredited11.jpg", "name": "Blazer, Annie"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/patton_b1.jpg", "name": "Burchett, Patton"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/mdaise5aedited.jpg", "name": "Daise, Michael"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/fitzgerald_thumb.jpg", "name": "Fitzgerald, Maureen"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/kirsh_Mary.jpg", "name": "Fraser Kirsh, Mary"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/galambushthumb.jpeg", "name": "Galambush, Julie"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/mmclaughlin1", "name": "McLaughlin, Mark"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/daminiphoto.jpg", "name": "Ogunnaike , Oludamini "},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/raphaelthumb.jpeg", "name": "Raphael, Marc Lee"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/Faraz_Sheikh1.png", "name": "Sheikh, Faraz"},
{"department": ["Religious Studies"], "pic": "http://www.wm.edu/as/religiousstudies/_images/faculty-images/vosethumb.jpeg", "name": "Vose, Kevin"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/buchanan-c-100.jpg", "name": "Buchanan, Camilla"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/burnet100.jpg", "name": "Burnet, Evie"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/charles_j.jpg", "name": "Charles, John"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/deschenes_m.jpg", "name": "Deschenes, Michael"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/harris_m.jpg", "name": "Harris, M. Brennan"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/kambis_k.jpg", "name": "Kambis, Kenneth"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/kohl_r.jpg", "name": "Kohl, Robert"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/looft_r.jpg", "name": "Looft-Wilson, Robin"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/mccoy_r.jpg", "name": "McCoy, Raymond"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/menefee-s tn.jpg", "name": "Menefee, Sarah"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/everhardt-a-100.jpg", "name": "Queen, Ashleigh Everhardt"},
{"department": ["Kinesiology"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/scott_a_thumb.jpg", "name": "Scott, Alison"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/benes_t.jpg", "name": "Benes, Kveta"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/bbcamp.jpg", "name": "Campbell, Bruce"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/hutton_w100x100.jpg", "name": "Hutton, William"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/koloski_l.jpg", "name": "Koloski, Laurie"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/leventhal_fix.jpg", "name": "Leventhal, Robert"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/levitan.jpg", "name": "Levitan, Kathrin"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/pacini_g1.jpg", "name": "Pacini, Giulia"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/panoussi_v100x100.jpg", "name": "Panoussi, Vassiliki"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/russianpostsov/images/maria_rogacheva.jpg", "name": "Rogacheva, Maria "},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/arthistory/images/Faculty/sayek_thumb2017.jpg", "name": "Zandi-sayek, Sibel"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/barnet-100x100.jpg", "name": "Barnet, Robert"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/bradley_e100pix.jpg", "name": "Bradley, Eric"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/biology/images/thumbnails/buchser_william_100px.jpg", "name": "Buchser, William"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/burk-100x100.jpg", "name": "Burk, Joshua A."},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/chemistry/images/faculty_staff/coleman200.jpg", "name": "Coleman, Randolph A."},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/cristol100pix.jpg", "name": "Cristol, Dan"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/appliedscience/images/misc_images/delnegro_thumg.jpg", "name": "Del Negro, Christopher"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/deschenes_m.jpg", "name": "Deschenes, Michael"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/dickter-100x100.jpg", "name": "Dickter, Cheryl"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/forestell_c", "name": "Forestell, Catherine"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/heideman100pix.jpg", "name": "Heideman, Paul"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/hilimire-2016-photo-100x100.jpg", "name": "Hilimire, Matthew"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/thumbnails/Pamzebrafish_thumb.jpg", "name": "Hunt, Pamela S."},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/Kieffaber-100x100.jpg", "name": "Kieffaber, Paul"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/kinesiology/images/faculty/thumbnails/looft_r.jpg", "name": "Looft-Wilson, Robin"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Patel 100px.jpg", "name": "Patel, Mainak"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/christyporter1.JPG", "name": "Porter, Christy"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/biology/images/directoryphotos/saha100pix.jpg", "name": "Saha, Margaret"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/neuroscience/images/faculty/thumbnails/smith_g.jpg", "name": "Smith, Greg"},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/directory/stevens-100x100.jpg", "name": "Stevens, Jennifer A."},
{"department": ["Neuroscience"], "pic": "http://www.wm.edu/as/psychology/images/vishton_p.jpeg", "name": "Vishton, Peter"},
{"department": ["Government"],  "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/blouet_thumb.jpg",  "name": "Blouet, Brian"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/cheng_thumb.jpg",  "name": "Cheng, T. J."},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/clemens1_thumb.jpg",  "name": "Clemens, Clay"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Cleveland_Thumbnail.jpg",  "name": "Cleveland, Clayton"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/faculty-directory/dessler_d.php",  "name": "Dessler, David"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/faculty-directory/devins_n.php",  "name": "Devins, Neal"},
{"department": ["Government"], "pic": "",  "name": "DiLorenzo, Matthew"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/faculty-directory/doherty_d.php",  "name": "Doherty, Daniel"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/faculty-directory/evans_l.php",  "name": "Evans, C. Lawrence"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/french_thumb.jpg",  "name": "French, Craig"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/gilmour_j_thumb.jpg",  "name": "Gilmour, John"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/hanson_thumb.jpg",  "name": "Hanson, Stephen"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/hart_thumb.jpg",  "name": "Hart, Sophia"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/lenneal%20henderson%20thumb.jpg",  "name": "Henderson, Lenneal"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Holmes%20Photo%20Thumbnail.png",  "name": "Holmes, Marcus"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/HowardThumb.jpg",  "name": "Howard, Chris"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/J_Kaplow_photo.jpg",  "name": "Kaplow, Jeff"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/lombardini_thumb.jpg",  "name": "Lombardini, John"},
{"department": ["Med-Ren"], "pic": "",  "name": "Blank, Paula"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/history/images/faculty/chouin.jpg",  "name": "Chouin, Gerard"},
{"department": ["Med-Ren"], "pic": "",  "name": "Conlee, John"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/history/images/faculty/daileader_p.jpg",  "name": "Daileader, Phil"},
{"department": ["Med-Ren"], "pic": "",  "name": "Greenia, George"},
{"department": ["Med-Ren"], "pic": "",  "name": "Hagedorn, Suzanne"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/history/images/faculty/thumbnails/homza_l100x100.jpg",  "name": "Homza, Lu Ann"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/classicalstudies/images/faculty/thumbnails/hutton_w100x100.jpg",  "name": "Hutton, William"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/history/images/faculty/stump.jpg",  "name": "Karakaya-Stump, Ayfer"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/arthistory/images/Faculty/Levesque_2013thumb.jpg",  "name": "Levesque, Catherine"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/english/images/minearthumb.jpg",  "name": "Minear, Erin"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/music/images/thumbnails/payne_t100x100.jpg",  "name": "Payne, Thomas"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/history/images/faculty/popper_contact.jpg",  "name": "Popper, Nicholas"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/english/images/potkaymthumb.jpg",  "name": "Potkay, Monica"},
{"department": ["Med-Ren"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/terukina_j_100.jpg",  "name": "Terukina, Jorge"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/film-media-studies/_images/bernard_tim.jpg",  "name": "Barnard, Timothy"},
{"department": ["Film and Media Studies"], "pic": "",  "name": "Begley, Varun"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/offices/apel/elearning/contacts/images/davis_troy.png",  "name": "Davis, Troy"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/english/images/JoyceThumbnail.jpg",  "name": "Joyce, Simon"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/english/images/kennedythumbnail.jpg",  "name": "Kennedy, Colleen"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/english/images/Knightthumbnail.jpg",  "name": "Knight, Arthur"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/english/images/Lowrythumb.jpg",  "name": "Lowry, Richard"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/arthistory/images/Faculty/palermo_charles_2013_thumb.jpg",  "name": "Palermo, Charles"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/axprok.jpg",  "name": "Prokhorov, Sasha"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/evprok.jpg",  "name": "Prokhorova, Elena"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/film-media-studies/_images/stadelmann-tanya.jpg",  "name": "Stadelmann, Tanya"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/stock-thumb.jpg",  "name": "Stock, Ann Marie"},
{"department": ["Film and Media Studies"], "pic": "",  "name": "Stoddard, Jeremy"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/jltay.jpg",  "name": "Taylor, Jennifer"},
{"department": ["Film and Media Studies"], "pic": "http://www.wm.edu/as/english/images/zuberthumbnail.jpg",  "name": "Zuber, Sharon"},
{"department": ["American Studies"], "pic": "",  "name": "Blakey, Michael "},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/arthistory/images/Faculty/Braddock%20at%20MoMA.jpg",  "name": "Braddock, Alan"},
{"department": ["American Studies"], "pic": "",  "name": "Brown, Chandos M."},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/english/images/donaldsonthumbnail.jpg",  "name": "Donaldson, Susan "},
{"department": ["American Studies"], "pic": "",  "name": "Gundaker, Grey "},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/english/images/Knightthumbnail.jpg",  "name": "Knight, Arthur"},
{"department": ["American Studies"], "pic": "",  "name": "Lelievre, Michelle"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/americanstudies/faculty/directoryimages/losh_liz.jpg",  "name": "Losh, Elizabeth"},
{"department": ["American Studies"], "pic": "",  "name": "McGovern, Charles"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/meyer.jpg",  "name": "Meyer, Leisa"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/rosen.jpg",  "name": "Rosen, Hannah"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/english/images/Sawayathumb.jpg",  "name": "Sawaya, Francesca"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/english/images/scholnickthumb.jpg",  "name": "Scholnick, Robert"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/english/images/thompsonthumb.jpg",  "name": "Thompson, Kara"},
{"department": ["American Studies"], "pic": "http://www.wm.edu/as/arthistory/images/webster-100x100.jpg",  "name": "Webster, Susan V."},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/arries_02.jpg",  "name": "Arries, Jonathan"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/mendez_j_thumb.jpg",  "name": "Bickham-Mendez, Jennifer "},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/blouet_thumb.jpg",  "name": "Blouet, Brian"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/cobuck.jpg",  "name": "Buck, Carla"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/globalstudies/latinamerican/faculty/yuiy.jpg",  "name": "Castillo, Victoria "},
{"department": ["Global Studies"], "pic": "",  "name": "Fisher, William"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/gosinmonikathumb.jpg",  "name": "Gosin, Monika"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/sociology/images/faculty/thumbnails/BrentKaup_thumb.jpg",  "name": "Kaup, Brent "},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/konefal.jpg",  "name": "Konefal, Betsy"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/teresa_thumb.jpg",  "name": "Longo, Teresa "},
{"department": ["Global Studies"], "pic": "",  "name": "Morell-Hart, Shanti"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/history/images/faculty/prado.jpg",  "name": "Prado, Fabricio"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/riofrio_j_100.jpg",  "name": "Riofrio, John"},
{"department": ["Global Studies"], "pic": "",  "name": "Root, Regina"},
{"department": ["Global Studies"], "pic": "",  "name": "Smith, Frederick"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/stock-thumb.jpg",  "name": "Stock, Ann Marie "},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/silvia.jpg",  "name": "Tandeciarz, Silvia"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/maliniak_d_thumb.jpg",  "name": "Maliniak, Dan"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/manna_thumb.jpg",  "name": "Manna, Paul"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/mcglennon_thumb.jpeg",  "name": "McGlennon, John"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/clairemckinney.jpg",  "name": "McKinney, Claire"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/mullen_thumb.jpg",  "name": "Mullen, Rani"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/nemacheck_thumb.jpg",  "name": "Nemacheck, Christine"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/A%20Oakes%20photo%202014%20edited.jpg",  "name": "Oakes, Amy"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/peterson_thumb.jpg",  "name": "Peterson, Sue"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/pickering_thumb.jpg",  "name": "Pickering, Paula"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/PoliquinThumb.jpg",  "name": "Poliquin, Etienne"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/rahman_thumb.jpg",  "name": "Rahman, Katherine"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/rapoport_thumb.jpg",  "name": "Rapoport, Ronald"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Roessler_thumb1.jpg",  "name": "Roessler, Philip"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/sasser_thumb1.jpg",  "name": "Sasser, Jackson"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/schwartz1_thumb.jpg",  "name": "Schwartz, Joel"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/settle_thumb.jpg",  "name": "Settle, Jaime"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/shulman_thumb.jpg",  "name": "Shushan, Debra"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/D%20Smith%20Photo%202014%20edited.jpg",  "name": "Smith, Dennis"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/sterling_thumb.jpg",  "name": "Sterling, Rebekah"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/Stow%20Thumbnail.jpg",  "name": "Stow, Simon"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/bolotnikov100.jpg",  "name": "Bolotnikov, Vladimir"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Chung%20small.jpg",  "name": "Chung, Yu-Min"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Day%202%20100px.jpg",  "name": "Day, Sarah"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/news_images/thumbnails/Delbos%20100px.jpg",  "name": "Delbos, Rachel"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/cary_h.JPG",  "name": "Humber, Cary"},
{"department": ["Mathematics"], "pic": "",  "name": "Iaci, Ross"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/JohnsonC2%20100px.jpg",  "name": "Johnson, Charles"},
{"department": ["Mathematics"], "pic": "",  "name": "Kim, Jiwon"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/news_images/thumbnails/Kincaid%20100px.jpg",  "name": "Kincaid, Rex"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Leemis2%20100px.jpg",  "name": "Leemis, Lawrence"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Li%20100px.jpg",  "name": "Li, Chi-Kwong"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Ninh%20100px.jpg",  "name": "Ninh, Anh"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Patel%20100px.jpg",  "name": "Patel, Mainak"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/rublein100.jpg",  "name": "Rublein, George"},
{"department": ["Mathematics"], "pic": "",  "name": "Sasinowska, Heather"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Shaw%20100px.jpg",  "name": "Shaw, Leah"},
{"department": ["American Studies"], "pic": "",  "name": "Weiss, M. Lynn"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/terukina_j_100.jpg",  "name": "Terukina, Jorge"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/globalstudies/images/faculty/Turits.jpg",  "name": "Turits, Richard"},
{"department": ["Global Studies"], "pic": "http://www.wm.edu/as/arthistory/images/webster-100x100.jpg",  "name": "Webster, Susan "},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/tierney_thumb.jpg",  "name": "Tierney, Michael"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/vanderveen_thumb.jpg",  "name": "van der Veen, Maurits"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/larrywilkerson_thumb.jpeg",  "name": "Wilkerson, Lawrence"},
{"department": ["Government"], "pic": "http://www.wm.edu/as/government/_images/faculty-photos/thumbnails/Zhang_Thumbnail.jpg",  "name": "Zhang, Hongyu"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Shi%20100px.jpg",  "name": "Shi, Junping"},
{"department": ["Mathematics"], "pic": "",  "name": "Swartz, Eric"},
{"department": ["Mathematics"], "pic": "",  "name": "Trefethen, Stephen"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Vasiliu2%20100px.jpg",  "name": "Vasiliu, Daniel"},
{"department": ["Mathematics"], "pic": "",  "name": "Vinroot, Ryan"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/Wang.JPG",  "name": "Wang, GuanNan"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Yu%20100px.jpg",  "name": "Yu, Gexin"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/Zapf%20100px.jpg",  "name": "Zapf, Marylou"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/zobin100.jpg",  "name": "Zobin, Nahum"},
{"department": ["Mathematics"], "pic": "http://www.wm.edu/as/mathematics/_images/directoryimages/thumbnails/anke10.jpg",  "name": "Zuylen, Anke van"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/arries_02.jpg",  "name": "Arries, Jonathan"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/Baker.jpg",  "name": "Baker, Christina"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/russian/Elena%20Beliaeva.jpg",  "name": "Beliaeva, Elena "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/cobuck.jpg",  "name": "Buck, Carla"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/bbcamp.jpg",  "name": "Campbell, Bruce "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/Carrion_PaulinaTN2.jpg",  "name": "Carrin, Paulina"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/francie-square.jpg",  "name": "Cate-Arries, Francie"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/cherkaoui.jpg",  "name": "Cherkaoui, Driss "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/french/compan.jpg",  "name": "Compan, Magali"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/japanese/Cronin11.jpg",  "name": "Cronin, Michael "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/jceise.jpg",  "name": "Eisele, John "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/about/contact/fauvel100.jpg",  "name": "Fauvel, Maryse "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/italian/home/Sergio.jpg",  "name": "Ferrarese, Sergio"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/bbginz-square.jpg",  "name": "Ginzbursky-Blum, Bella"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/home/Gully_Profile-1-150x150.jpg",  "name": "Glly, Jennifer"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/chinese/Han%20Xu.jpg",  "name": "Han, Xu"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/chinese/MichaelHill.jpg",  "name": "Hill, Michael"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/french/hugonny1.jpg",  "name": "Hugonny, Julie"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/chinese/Calvin%20Hui%201.jpg",  "name": "Hui, Calvin"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/Veronika%20Jeltsch.jpg",  "name": "Jeltsch, Veronika "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanthumb2/txkato.jpg",  "name": "Kato, Tomoko "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/aiko.jpg",  "name": "Kitamura, Aiko "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanthumb2/kmkuli.jpg",  "name": "Kulick, Katherine "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/french/Clement_LeCoz.jpg",  "name": "Le Coz, Clement"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/angela_leruth.jpg",  "name": "Leruth, Angela "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanthumb2/mfleru.jpg",  "name": "Leruth, Michael "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/leventhal_fix.jpg",  "name": "Leventhal, Robert "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/teresa_thumb.jpg",  "name": "Longo, Teresa"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/lontor.jpg",  "name": "Lontor, Peter"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/chinese/chun.jpg",  "name": "Lu, Chun-yu"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/chinese/LuLu_thmb.jpg",  "name": "Lu, Lu"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/italian/SaraMattavelli.jpg",  "name": "Mattavelli, Sara"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/MarianaMeloVega.jpg",  "name": "Melo-Vega, Mariana"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/hispanic/Pablo%20Moral.jpg",  "name": "Moral, Pablo"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/russian/Mulcahy.R2.jpg",  "name": "Mulcahy, Robert"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/Kim%20Mutmann.jpg",  "name": "Mutmann, Kim"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/pacini_g1.jpg",  "name": "Pacini, Giulia"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/axprok.jpg",  "name": "Prokhorov, Alexander "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/evprok.jpg",  "name": "Prokhorova, Elena "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/french/Nathan%20Rabalais.jpg",  "name": "Rabalais, Nathan "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/riofrio_j_100.jpg",  "name": "Riofrio, John"},
{"department": ["Modern Languages"], "pic": "",  "name": "Root, Regina"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/japanese/Sakuma_Norie.jpg",  "name": "Sakuma, Norie"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/carmen.jpg",  "name": "Sanchis-Sinisterra, Carmen"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/japanese/sasaki.jpg",  "name": "Sasaki, Tomoyuki"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/italian/monica02a.jpg",  "name": "Seger, Monica "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/arabic/sheehi_12092014492.jpg",  "name": "Sheehi, Stephen"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/german/RebekahSlodounik.jpg",  "name": "Slodounik, Rebekah"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/italian/Spina_Alessandro.jpg",  "name": "Spina, Alessandro"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/stock-thumb.jpg",  "name": "Stock, Ann Marie"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanthumb2/qsu.jpg",  "name": "Su, Qian"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/silvia.jpg",  "name": "Tandeciarz, Silvia "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/tang_y.jpg",  "name": "Tang, Yanfang "},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/modlanguagesthumb1/jltay.jpg",  "name": "Taylor, Jennifer"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/images/faculty/thumbnails/terukina_j_100.jpg",  "name": "Terukina, Jorge"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/french/Vozel.jpg",  "name": "Vozel, Franois-Nicolas"},
{"department": ["Modern Languages"], "pic": "http://www.wm.edu/as/modernlanguages/faculty/arabic/mona_zaki02.jpg",  "name": "Zaki, Mona"},
{"department": ["Linguistics"], "pic": "",  "name": "Bragdon, Kathleen"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/charity_hudley2.jpg",  "name": "Charity Hudley, Anne"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/cochranethumbnail.jpg",  "name": "Cochrane, Leslie"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/linguistics/images/faculty/thumbnails/kaitlyn_harrigan_thumb.jpg",  "name": "Harrigan, Kaitlyn"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/lundenthumb.jpg",  "name": "Lunden, Anya"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/martin_j_thumbnail.jpg",  "name": "Martin, Jack B."},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/osiapemthumb.jpg",  "name": "Osiapem, Iyabo"},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/parkerthumb.jpg",  "name": "Parker, Dan"},
{"department": ["Linguistics"], "pic": "",  "name": "Reed, Ann M."},
{"department": ["Linguistics"], "pic": "https://www.wm.edu/as/english/images/Tolly2.jpg",  "name": "Taylor, Talbot J."},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/abraham_c_thumb.jpg", "name": "Abraham, Chon"},
{"department": ["Faculty & Research"], "pic": "images/agnew_j_thumb.jpg", "name": "Agnew, Julie"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/allred_b_thumb.jpg", "name": "Allred, Brent"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/ash_r_thumb.jpg", "name": "Ash, Richard"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/atanasov_v_thumb.jpg", "name": "Atanasov, Vladimir"},
{"department": ["Faculty & Research"], "pic": "images/bertolini_m_thumb.jpg", "name": "Bertolini, Michelle"},
{"department": ["Faculty & Research"], "pic": "images/blossom_p_thumb.jpg", "name": "Blossom, Paul"},
{"department": ["Faculty & Research"], "pic": "images/cypher_icon.jpg", "name": "Boone, Tonya"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/boschen_j_thumb1.jpg", "name": "Boschen, John"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/bradley_j_thumb.jpg", "name": "Bradley, James"},
{"department": ["Faculty & Research"], "pic": "images/cypher_icon.jpg", "name": "Bryce, Herrington"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/busbee_h_thumb.jpg", "name": "Busbee, Howard"},
{"department": ["Faculty & Research"], "pic": "images/carboni_i_thumb1.jpg", "name": "Carboni, Inga"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/carleton_j_thumb.jpg", "name": "Carleton, James A."},
{"department": ["Faculty & Research"], "pic": "images/cici_g_2015_thumb.jpg", "name": "Cici, Gjergji"},
{"department": ["Faculty & Research"], "pic": "images/crafford_thumb.jpg", "name": "Crafford, Glenn"},
{"department": ["Faculty & Research"], "pic": "images/cumby_p_thumb.jpg", "name": "Cumby, Patrick"},
{"department": ["Faculty & Research"], "pic": "images/dafashy_w_thumb.jpg", "name": "Dafashy, Wagih"},
{"department": ["Faculty & Research"], "pic": "images/diaz_j_thumb.jpg", "name": "Diaz, Jamie"},
{"department": ["Faculty & Research"], "pic": "images/edmiston_d_thumb1.jpg", "name": "Edmiston, Dawn"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/flood_r_thumb.jpg", "name": "Flood, Richard"},
{"department": ["Faculty & Research"], "pic": "images/foster_e_thumb.jpg", "name": "Foster, Elizabeth"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/ganeshan_r_thumb.jpg", "name": "Ganeshan, Ram"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/geary_w_thumb.jpg", "name": "Geary, William"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/gibson_s_thumb.jpg", "name": "Gibson, Scott"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/gore_p_thumb.jpg", "name": "Gore, Peter"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/guerrero_h_thumb.jpg", "name": "Guerrero, Hector"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/guthrie_sq.jpg", "name": "Guthrie, Katherine"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/haltiner_j_thumb.jpg", "name": "Haltiner, James"},
{"department": ["Faculty & Research"], "pic": "images/henshaw_g_thumb.jpg", "name": "Henshaw, Graham"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/hess_r_thumb.jpg", "name": "Hess, Ronald L."},
{"department": ["Faculty & Research"], "pic": "images/hewitt_d_thumb.jpg", "name": "Hewitt, Deborah"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/holmlin_r_thumb.jpg", "name": "Holmlin, Rex"},
{"department": ["Faculty & Research"], "pic": "images/howard_m_thumb.jpg", "name": "Howard, Margot"},
{"department": ["Faculty & Research"], "pic": "images/jelinek_s_thumb.jpg", "name": "Jelinek, Ph.D., Mariann"},
{"department": ["Faculty & Research"], "pic": "images/johnson_hall_t _thumb.jpg", "name": "Johnson-Hall, Tracy"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/jones_d_thumb.jpg", "name": "Jones, Denise"},
{"department": ["Faculty & Research"], "pic": "images/kohli_r_thumb1.jpg", "name": "Kohli, Rajiv"},
{"department": ["Faculty & Research"], "pic": "images/kourmadis_j_thumb1.jpg", "name": "Kourmadas, James"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/langholtz_h_thumb.jpg", "name": "Langholtz, Harvey"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/locke_k_thumb.jpg", "name": "Locke, Karen"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/long_david_thumb.jpg", "name": "Long, David"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/luchs_m_thumb.jpg", "name": "Luchs, Michael"},
{"department": ["Faculty & Research"], "pic": "images/marble_h_thumb.jpg", "name": "Marble, Hugh"},
{"department": ["Faculty & Research"], "pic": "images/martin_h_thumb.jpg", "name": "Martin, Harold"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/mccoy_s_thumb.jpg", "name": "McCoy, Scott"},
{"department": ["Faculty & Research"], "pic": "images/mellor_j.jpg", "name": "Mellor, Jennifer M."},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/merrick_j_thumb.jpg", "name": "Merrick, John"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/metcalfe_l_thumb.jpg", "name": "Metcalfe, LD"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/monark_r_thumb.jpg", "name": "Monark, Ronald J."},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/murray_d_thumb.jpg", "name": "Murray, David"},
{"department": ["Faculty & Research"], "pic": "images/njoroge_k_thumb.jpg", "name": "Njoroge, Kenneth"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/olver_j_thumb.jpg", "name": "Olver, James"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/pearson_r_thumb.jpg", "name": "Pearson, Roy"},
{"department": ["Faculty & Research"], "pic": "images/petrovits_c_thumb.jpg", "name": "Petrovits, Christine"},
{"department": ["Faculty & Research"], "pic": "images/picconi_m_thumb.jpg", "name": "Picconi, Marc "},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/pulley_l_thumb.jpg", "name": "Pulley, Larry"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/rahtz_d_thumb.jpg", "name": "Rahtz, Don"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/ring_l_thumb.jpg", "name": "Ring, Lawrence"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/robeson_b_thumb.jpg", "name": "Robeson, Franklin Bud"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/rosenfeld_c_thumb.jpg", "name": "Rosenfeld, Claire"},
{"department": ["Faculty & Research"], "pic": "images/rossiter_l_thumb.jpg", "name": "Rossiter, Louis"},
{"department": ["Faculty & Research"], "pic": "images/seiler_n_thumb.jpg", "name": "Seiler, Michael J."},
{"department": ["Faculty & Research"], "pic": "images/shane_p_thumb.jpg", "name": "Shane, Philip"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/sims_r_thumb.jpg", "name": "Sims, Ronald"},
{"department": ["Faculty & Research"], "pic": "images/slade_a_thumb.jpg", "name": "Slade, Allen"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/smith_j_thumb.jpg", "name": "Smith, James"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/smith_k_thumb.jpg", "name": "Smith, Kimberly"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/solomon_r_thumb.jpg", "name": "Solomon, Robert"},
{"department": ["Faculty & Research"], "pic": "images/stauffer_w_thumb.jpg", "name": "Stauffer, William"},
{"department": ["Faculty & Research"], "pic": "images/stephens_r_thumb.jpg", "name": "Stephens, Rachel"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/stewart_w_thumb.jpg", "name": "Stewart, William"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/stowers_r_thumb.jpg", "name": "Stowers, Robert"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/strong_j_thumb.jpg", "name": "Strong, John"},
{"department": ["Faculty & Research"], "pic": "images/stump_m_thumb.jpg", "name": "Stump, Michael"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/swan_s_thumb1.jpg", "name": "Swan, K. Scott"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/szykman_l_thumb.jpg", "name": "Szykman, Lisa"},
{"department": ["Faculty & Research"], "pic": "images/tack_thumb.png", "name": "Tack, Carl"},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/waxman_n_thumb.jpg", "name": "Waxman, Ned W."},
{"department": ["Faculty & Research"], "pic": "images/faculty/thumbs/white_g_thumb.jpg", "name": "White, G. Thomas"},
{"department": ["Faculty & Research"], "pic": "images/white_k_thumb.jpg", "name": "White, Ken"},
{"department": ["Faculty & Research"], "pic": "images/wilck_j_thumb.jpg", "name": "Wilck, Joseph"},
{"department": ["Faculty & Research"], "pic": "images/williams_b_thumb.jpg", "name": "Williams, Bob"},
{"department": ["Faculty & Research"], "pic": "images/wilson_j_thumb.jpg", "name": "Wilson, Jeanne"},
{"department": ["Faculty & Research"], "pic": "images/woods_a_sm.jpg", "name": "Woods, Alex"}

]';

	$("thead").find("tr").each(function() {
        $(this).find("th").eq(4).after("<th>Picture</th>");
    });
    $("tbody").find("tr").each(function() {
        var professorName = $(this).find("td").eq(4).html();
        $(this).find("td").eq(4).after(
            "<td><pre>"+professorName+"</pre></td>");    
        }
    );

})();
